name: 'Publish to GitHub Releases'

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Test
        run: ./gradlew test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build
        run: ./gradlew shadowJar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/java-discord-oauth2-api-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}